---
version: 2
jobs:
  build:
    docker:
      - image: jtheo/devops
    parallelism: 4
    environment:
      DEPLOY_IN_MASTER: 1
    steps:
      - checkout
      - run:
          name: test pub variables
          command: echo "DEPLOY_IN_MASTER => ${DEPLOY_IN_MASTER} <="
      - run: |
            cd
            git clone https://github.com/jtheo/jtheo_stuff.git
            echo '<some><example>jtheo</example></some>' |  python /root/jtheo_stuff/xml2json


      - run:
          name: Test background jobs
          command: time bash dummy.sh

      - run:
          name: Report Time Execution
          command: bash report.sh

      - run:
          name: Show output Err Logs
          command: bash show_logs.sh Err

      - run:
          name: Show output Warn Logs
          command: bash show_logs.sh Warn

      - run:
          name: Show output Ok Logs
          command: bash show_logs.sh Ok
