version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install dependecies
          command: bash set_env.sh
  
      - run:
          name: Test background jobs
          command: bash dummy.sh
  
      - run:
          name: Show output
          command: bash show_logs.sh
  